<Project>
  <PropertyGroup>
    <NuclearOptionDir Condition="'$(NuclearOptionDir)' == ''">$(HOME)/.local/share/Steam/steamapps/common/Nuclear Option</NuclearOptionDir>

    <ManagedDir Condition="'$(ManagedDir)' == '' and Exists('$(NuclearOptionDir)/NuclearOption_Data/Managed')">$(NuclearOptionDir)/NuclearOption_Data/Managed</ManagedDir>
    <ManagedDir Condition="'$(ManagedDir)' == '' and Exists('$(NuclearOptionDir)/NuclearOptionServer_Data/Managed')">$(NuclearOptionDir)/NuclearOptionServer_Data/Managed</ManagedDir>
  </PropertyGroup>

  <Target Name="ValidateManagedDir" BeforeTargets="ResolveReferences">
    <Error Condition="!Exists('$(ManagedDir)/Assembly-CSharp.dll')"
           Text="ManagedDir is invalid or missing: $(ManagedDir)" />
  </Target>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="Mirage">
      <HintPath>$(ManagedDir)/Mirage.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>$(ManagedDir)/Rewired_Core.dll</HintPath>
      <Private>false</Private>
      <Publicize>true</Publicize>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedDir)/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedDir)/Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
